Initialisation du jeu aléatoire :

In [6]:
import numpy as np
import random

def initialisation():
    plateau_initial = []
    while len(plateau_initial) < 9:
        a = random.randint(0, 8)
        if a not in plateau_initial:
            plateau_initial.append(a)

    return plateau_initial

print(initialisation())


[[1 8 0]
 [3 2 4]
 [6 5 7]]
