Initialisation du jeu aléatoire :

In [6]:
import numpy as np
import random

def initialisation():
    explore = []
    while len(explore) < 9:
        a = random.randint(0, 8)
        if a not in explore:
            explore.append(a)
    
    plateau_initial = np.array(explore).reshape((3,3))
    return plateau_initial

print(initialisation())


[[1 8 0]
 [3 2 4]
 [6 5 7]]
